directionalLights:
  - direction: { x: -1.0, y: -1.0, z: 0.0 }
    ambient: { x: 0.1, y: 0.1, z: 0.1 }
    diffuse: { x: 0.7, y: 0.7, z: 0.7 }
    specular: { x: 1.0, y: 1.0, z: 1.0 }
    lightColor: { x: 1.0, y: 1.0, z: 1.0 }
  - direction: { x: 0.0, y: -1.0, z: -1.0 }
    ambient: { x: 0.1, y: 0.1, z: 0.1 }
    diffuse: { x: 0.5, y: 0.5, z: 0.5 }
    specular: { x: 1.0, y: 1.0, z: 1.0 }
    lightColor: { x: 1.0, y: 1.0, z: 1.0 }
